const express=require("express");
const router=express.Router();
const authMiddleware=require("../middleware/authMiddleware");
const rateLimiter=require("../middleware/rateLimiter");
const linkController=require("../controllers/linkController");
const analyticsController=require("../controllers/analyticsController");
router.post("/",rateLimiter,authMiddleware,linkController.createLink);
router.get("/",authMiddleware,linkController.getAllLinks);
router.get("/:id",authMiddleware,linkController.getLink);
router.put("/:id",authMiddleware,linkController.updateLink);
router.delete("/:id",authMiddleware,linkController.deleteLink);
router.get("/:id/analytics",authMiddleware,analyticsController.getAnalytics);
module.exports=router;